name: Cargo Build & Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
#  RUSTFLAGS: "-Dwarnings"

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
#      - run: rustup update stable && rustup default stable
      - run: cargo test
      - run: cargo clippy --all-targets --all-features
