name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: "-Dwarnings"

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Test
        run: cargo test --all-targets --all-features
      - name: Lint
        run: cargo clippy --all-targets --all-features

  coverage:
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-tarpaulin
      - uses: Swatinem/rust-cache@v2
      - name: Generate code coverage
        run: cargo tarpaulin --all-targets --all-features --timeout 120 --out xml --skip-clean --target-dir target/tarpaulin
      - name: Upload to coveralls.io
        uses: coverallsapp/github-action@v2
        with:
          fail-on-error: false

  build_docker_image:
    needs: build_and_test
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/docker-build.yml
    permissions:
      contents: read
      packages: write
