name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
#  RUSTFLAGS: "-Dwarnings" # todo fix deprecation warning

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-tarpaulin
      - uses: Swatinem/rust-cache@v2
      - name: Test
        run: cargo test --all-targets --all-features
      - name: Lint
        run: cargo clippy --all-targets --all-features
      - name: Generate code coverage
        run: cargo tarpaulin --all-targets --all-features --timeout 120 --out xml --target-dir target/tarpaulin --skip-clean
      - name: Upload to coveralls.io
        uses: coverallsapp/github-action@v2
