name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
#  RUSTFLAGS: "-Dwarnings" # todo fix deprecation warning

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Test
        run: cargo test --all-features
      - name: Lint
        run: cargo clippy --all-targets --all-features

  coverage:
    needs: build_and_test
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:0.27.1
      options: --security-opt seccomp=unconfined
    steps:
      - uses: actions/checkout@v4
      - name: Generate code coverage
        run: cargo +nightly tarpaulin --all-features --workspace --timeout 120 --out xml
      - name: Upload to coveralls.io
        uses: coverallsapp/github-action@v2
